CREATE TABLE MESSAGE(
   ID INTEGER PRIMARY KEY     NOT NULL,
   SENDER           INT    NOT NULL,
   RECEIVER           INT    NOT NULL,
   CONTENT           TEXT    NOT NULL,
   TIMESTAMP            INT     NOT NULL
);

CREATE TABLE USER(
   ID INTEGER PRIMARY KEY     NOT NULL,
   NAME           TEXT    NOT NULL
);


INSERT INTO USER (ID,NAME) VALUES (1, 'Paul');
INSERT INTO USER (ID,NAME) VALUES (2, 'Joe');
INSERT INTO USER (ID,NAME) VALUES (3, 'Alice');
INSERT INTO USER (ID,NAME) VALUES (4, 'Bob');


INSERT INTO MESSAGE (SENDER, RECEIVER, CONTENT, TIMESTAMP)
VALUES (1, 2, 'hi', 1557867338);
INSERT INTO MESSAGE (SENDER, RECEIVER, CONTENT, TIMESTAMP)
VALUES (1, 2, 'how are you?', 1557867338);
INSERT INTO MESSAGE (SENDER, RECEIVER, CONTENT, TIMESTAMP)
VALUES (2, 1, 'hi', 1557867338);
INSERT INTO MESSAGE (SENDER, RECEIVER, CONTENT, TIMESTAMP)
VALUES (2, 1, 'I am fine', 1557867338);

